#!/bin/bash
if [ "$1" != "" ];
then
printf "\n ****************Initiating the process************* \n\n"
printf "\n ****************You need to enter the password for $1************* \n\n"
ssh uid@$1 mkdir -p .ssh

#Command to create the pub file ----- "ssh-keygen -t rsa"

cat /home/uid0/.ssh/id_rsa.pub | ssh uid@$1 'cat >> .ssh/authorized_keys'
ssh uid@$1 "chmod 700 .ssh; chmod 640 .ssh/authorized_keys"
else
printf "\n"
echo "Please input an argument after invoking the script, for eg:- ./passwordless_connection (Server IP)"
fi
